config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks

  root to: redirect('/bookmarks')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :url, :title, presence: true
  validates :url, url: true

  belongs_to :site

  before_validation :handle_site_grouping

  private

  def handle_site_grouping
    return unless url.present?

    self.site = SiteManager.new(self).call
  end
end

app/models/site.rb
class Site < ApplicationRecord
  validates :url, presence: true, url: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action do
    # TODO: Facade, better way to build SQL query
    # NOTE: Check up against sql injection
    query = params[:search] ? params[:search][:query] : nil
    @bookmarks = BookmarkFilterer.new(query).call
    @sites = Site.where(id: @bookmarks.pluck(:site_id))
  end

  def index
    @new_bookmark = Bookmark.new
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @new_bookmark = Bookmark.new(bookmark_params)

    if @new_bookmark.save
      redirect_to root_url
    else
      render :index
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.update(bookmark_params)
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_html_class
    return 'css-debug' if params['css-debug'] == 'please'

    ''
  end
end

app/views/bookmarks/_bookmark.html.haml
%li.bookmark-list__item
  %a.bookmark-list__link{ href: bookmark.url }
    = bookmark.title

  %a.bookmark-list__edit{ href: edit_bookmark_path(bookmark) }
    = fa_icon('edit')

app/views/bookmarks/_form.html.haml
= simple_form_for bookmark, html: { class: [html_class, ('active' if bookmark.errors.any?)] } do |f|
  %h2= headline

  = f.input :title
  = f.input :url
  = f.input :shortening

  .form-btn-group
    = f.button :submit, class: 'form-submit'
    %button.form-cancel{ type: 'button' } Cancel

app/views/bookmarks/_site.html.haml
%h1= site.url

%ul.bookmark-list
  = render site.bookmarks

app/views/bookmarks/edit.html.haml
.bookmark-edit__page
  = render 'form', bookmark: @bookmark, headline: "Edit #{@bookmark.title}", html_class: 'bookmark-form--edit'

app/views/bookmarks/index.html.haml
.bookmark-list__page
  %h1.bookmark-list__heading
    Your bookmarks
    %button.bookmark-add-btn= fa_icon('plus')

  = render 'form', bookmark: @new_bookmark, headline: 'New bookmark', html_class: 'bookmark-form--new'

  = simple_form_for :search, url: bookmarks_path, method: :get, html: { class: 'bookmark-list__search-form' } do |f|
    = f.input :query, label: false, placeholder: 'Filter', required: false
    = f.button :button, class: 'bookmark-list__search-form__submit' do
      = fa_icon('search')

  %ul.bookmark-list
    = render @sites

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{ name: 'viewport', content: "width=device-width, initial-scale=1" }/

    %title Bookmanon

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = csrf_meta_tags

  %body{ class: body_html_class }
    %nav.topbar
      %a.topbar__name{ href: bookmarks_path } Bookmanon

    = yield

app/views/sites/_site.html.haml
%h2.bookmark-list__site-url= site.url

%ul.bookmark-list__bookmarks
  = render site.bookmarks